baseURL = 'rinnebuehl.de'
languageCode = 'en-us'
title = 'Rinnebuehl.de'
theme = "uBlogger"

[params]
  # uBlogger theme version
  version = "2.0.X"

  SEOTitle = "Rinnebuehl Blog"

  title_404 = "We couldn't find what you were looking for..."

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/post/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1


# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration
    noClasses = false