baseURL = 'https://rinnebuehl.de/'
defaultContentLanguage = "de"
languageCode = 'de'
title = 'Rinnebuehl.de'
theme = "uBlogger"
googleAnalytics = "G-H1KL9HPH4X"

# whether to use robots.txt
# 是否使用 robots.txt
enableRobotsTXT = true

[params]
  # uBlogger theme version
  version = "2.0.X"
  defaultTheme = "auto"

  SEOTitle = "Rinnebuehl Blog"
  title_404 = "Bist du so dicht, dass du nicht mal ne URL richtig eingeben kannst ?"


# Header config
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    # uBlogger NEW | 0.2.0 Header title config
    [params.header.title]
      # URL of the LOGO
      # logo = "/images/logo.jpeg"
      # title name
      name = "Rinnebuehl Blog"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""

 # Footer config
  # 页面底部信息配置
  [params.footer]
    enable = true
    # Custom content (HTML format is supported)
    # 自定义内容 (支持 HTML 格式)
    custom = ''
    # whether to show Hugo and theme info
    # 是否显示 Hugo 和主题信息
    hugo = true
    # whether to show copyright info
    # 是否显示版权信息
    copyright = true
    # whether to show the author
    # 是否显示作者
    author = true
    # site creation time
    # 网站创立年份
    since = 2022
    # license info (HTML format is supported)
    # 许可协议信息 (支持 HTML 格式)
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

# Home page config
  [params.home]
    # uBlogger NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/images/logo.jpeg"
      # uBlogger CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = "Rinnebuehl Blog "
      # subtitle shown in home page
      subtitle = "Wiki des betrunkenen Mannes"
      # whether to show social links
      social = true
      # uBlogger NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
      # uBlogger DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false

 # Social config about the author
  [params.social]
    Instagram = "rinnebuehlbar/"
    Snapchat = "rinnebuehlbar"
    GitHub = "rinnebuehl"

# {{< version 0.2.0 changed >}} Page config
  [params.page]
    # {{< version 1.0.0 new >}} main subject for articles, by default classic. {{< link "/theme-documentation-content/#theme" "more on themes" >}}}
    theme = "classic"
    # {{< version 0.2.0 >}} whether to hide a page from home page
    hiddenFromHomePage = false
    # {{< version 0.2.0 >}} whether to hide a page from search results
    hiddenFromSearch = false
    # {{< version 1.2.0 new >}} Allows you to hide the preview image on the article page
    hiddenFeaturedImage = false
    # {{< version 0.2.0 >}} whether to enable twemoji
    twemoji = false
    # whether to enable lightgallery
    lightgallery = false
    # {{< version 0.2.0 >}} whether to enable the ruby extended syntax
    ruby = true
    # {{< version 0.2.0 >}} whether to enable the fraction extended syntax
    fraction = true
    # {{< version 0.2.0 >}} whether to enable the fontawesome extended syntax
    fontawesome = true
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = true
    # {{< version 0.2.4 >}} whether to show the full text content in RSS
    rssFullText = false
    # {{< version 1.1.0 new >}} Post display settings on the page
    [params.summary]
      # {{< version 1.1.0 new >}} Display previews on the page of posts
      hiddenImage = false
      # {{< version 1.1.0 new >}} Allows you to hide the description
      hiddenDescription = false
      # {{< version 1.1.0 new >}} Allows you to hide the title
      hiddenTitle = false
    # {{< version 1.1.0 new >}} Tag display settings
    [params.summary.tags]
      # {{< version 1.1.0 new >}} One of the options for displaying tags
      theme = "image"
      # {{< version 1.1.0 new >}} Text color
      color = "white"
      # {{< version 1.1.0 new >}} Backing color
      background = "black"
      # {{< version 1.1.0 new >}} Tag transparency
      transparency = 0.9
    # {{< version 1.2.0 new >}} Fasting time display
    [params.timeAgo]
      enable = "false"
      lang = "de"
    [params.page.share]
      enable = false
      Twitter = false
      Facebook = false
      Linkedin = false
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = false
      Digg = false
      Stumbleupon = false
      Flipboard = false
      Weibo = false
      Renren = false
      Myspace = false
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false
    # {{< version 0.2.7 >}} Third-party library config
    [params.page.library]
      [params.page.library.css]
        # someCSS = "some.css"
        # located in "assets/"
        # Or
        # someCSS = "https://cdn.example.com/some.css"
      [params.page.library.js]
        # someJavascript = "some.js"
        # located in "assets/"
        # Or
        # someJavascript = "https://cdn.example.com/some.js"


[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1



# Markup related configuration in Hugo
# Hugo 解析文档的配置
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  # Table Of Contents settings
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
